# Generated by Django 2.0 on 2017-12-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batelada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batelada', models.IntegerField(default=0)),
                ('OG', models.IntegerField(default=0)),
                ('FG', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0, verbose_name='volume [L]')),
                ('data', models.DateTimeField(verbose_name='data da batelada')),
                ('estilo', models.CharField(max_length=128)),
                ('cervejeiro', models.CharField(max_length=128)),
                ('marca', models.CharField(max_length=128)),
                ('obs', models.TextField(verbose_name='observações')),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.IntegerField(default=0)),
                ('SG', models.IntegerField(default=0)),
                ('data', models.DateTimeField(verbose_name='data da medida')),
                ('pressao', models.IntegerField(default=0, verbose_name='Pressão [bar]')),
                ('temeratura', models.IntegerField(default=0, verbose_name='Temperatura [°C]')),
                ('obs', models.TextField(verbose_name='observações')),
                ('batelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.Batelada')),
            ],
        ),
    ]
