# Generated by Django 2.0 on 2017-12-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medida',
            name='medida',
        ),
    ]
