# Generated by Django 2.0 on 2018-01-15 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoramento', '0003_batelada_tanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='batelada',
            name='autor',
            field=models.ForeignKey(default='hi', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batelada',
            name='FG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='batelada',
            name='OG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='batelada',
            name='volume',
            field=models.FloatField(default=0, verbose_name='volume [L]'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='SG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medida',
            name='pressao',
            field=models.FloatField(default=0, verbose_name='Pressão [bar]'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='temeratura',
            field=models.FloatField(default=0, verbose_name='Temperatura [°C]'),
        ),
    ]
