# Generated by Django 2.0 on 2018-01-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_auto_20180115_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batelada2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batelada', models.IntegerField(default=0)),
                ('tanque', models.IntegerField(default=0)),
                ('OG', models.FloatField(default=0)),
                ('FG', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0, verbose_name='volume [L]')),
                ('data', models.DateTimeField(verbose_name='data da batelada')),
                ('estilo', models.CharField(max_length=128)),
                ('cervejeiro', models.CharField(max_length=128)),
                ('marca', models.CharField(max_length=128)),
                ('obs', models.TextField(verbose_name='observações')),
            ],
        ),
        migrations.CreateModel(
            name='Medida2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SG', models.FloatField(default=0)),
                ('data', models.DateTimeField(verbose_name='data da medida')),
                ('pressao', models.FloatField(default=0, verbose_name='Pressão [bar]')),
                ('temeratura', models.FloatField(default=0, verbose_name='Temperatura [°C]')),
                ('obs', models.TextField(verbose_name='observações')),
            ],
        ),
        migrations.RemoveField(
            model_name='batelada',
            name='autor',
        ),
        migrations.AddField(
            model_name='medida2',
            name='batelada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.Batelada'),
        ),
    ]
